server:
  port: 80

spring:
  application:
    name: cloud-order-service
# 和eureka组合使用
eureka:
  client:
    register-with-eureka: true # 不注册进eureka服务中心
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/,http://127.0.0.1:7002/eureka/


#设置feign客户端超时时间(OpenFeign默认支持ribbon)
ribbon:
#  #指的是建立连接所用的时间，适用于网络状况正常的情况下, 两端连接所用的时间
  ReadTimeout: 5000
#  #指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000

logging:
  level:
    # feign日志以 debug 级别监控 com.atguigu.springcloud.service.PaymentFeignService 接口
    com.atguigu.springcloud.service.PaymentFeignService: debug
